version: '2'

services:
  consul:
    image: consul:1.9.1
    command: ["consul", "agent", "-config-file=/config/config.hcl", "-config-dir=/config"]
    volumes:
    - "./consul_config:/config"
    ports:
    - 8500:8500
    networks:
      wsbridge:
        ipv4_address: 10.20.0.2
  front-end:
    image: gcr.io/up9-docker-hub/front-end:test
    labels:
      com.up9.tapped: true
    #image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    restart: always
    ports:
    - 8079:8079
    environment:
        - CATALOGUE_BASE_URL=http://127.0.0.1:15400
        - USER_BASE_URL=http://127.0.0.1:15100
        - ORDERS_BASE_URL=http://127.0.0.1:15200
        - CARTS_BASE_URL=http://127.0.0.1:15300
    cap_drop:
      - all
    read_only: true
    networks:
      wsbridge:
        ipv4_address: 10.20.0.10
  front-end_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/front-end.hcl
      CENTRAL_CONFIG: /central_config/front-end.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "front-end_v1"]
    network_mode: "service:front-end"
  edge:
    hostname: edge
    image: nginx
    ports:
    - 8000:8000
    volumes:
    - "./service_config/etc.nginx:/etc/nginx"
    networks:
      wsbridge:
        ipv4_address: 10.20.0.9
  edge_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/edge.hcl
      CENTRAL_CONFIG: /central_config/edge.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "edge_v1"]
    network_mode: "service:edge"
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    labels:
      com.up9.tapped: true
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    networks:
      wsbridge:
        ipv4_address: 10.20.0.11
  catalogue_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/catalogue.hcl
      CENTRAL_CONFIG: /central_config/catalogue.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "catalogue_v1"]
    network_mode: "service:catalogue"
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      wsbridge:
        ipv4_address: 10.20.0.111
  carts:
    image: weaveworksdemos/carts:0.4.8
    labels:
      com.up9.tapped: true
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      wsbridge:
        ipv4_address: 10.20.0.12
  carts_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/carts.hcl
      CENTRAL_CONFIG: /central_config/carts.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "carts_v1"]
    network_mode: "service:carts"
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      wsbridge:
        ipv4_address: 10.20.0.112
  orders:
    image: gcr.io/up9-docker-hub/orders:test
    #image: weaveworksdemos/orders:0.4.7
    labels:
      com.up9.tapped: true
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - PAYMENT_BASE_URL=http://127.0.0.1:15500
      - SHIPPING_BASE_URL=http://127.0.0.1:15600
    networks:
      wsbridge:
        ipv4_address: 10.20.0.13
  orders_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/orders.hcl
      CENTRAL_CONFIG: /central_config/orders.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "orders_v1"]
    network_mode: "service:orders"
  orders-db:
    image: mongo:3.4
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      wsbridge:
        ipv4_address: 10.20.0.113
  shipping:
    image: weaveworksdemos/shipping:0.4.8
    labels:
      com.up9.tapped: true
    hostname: shipping
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      wsbridge:
        ipv4_address: 10.20.0.14
  shipping_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/shipping.hcl
      CENTRAL_CONFIG: /central_config/shipping.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "shipping_v1"]
    network_mode: "service:shipping"
  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      wsbridge:
        ipv4_address: 10.20.0.101
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    networks:
      wsbridge:
        ipv4_address: 10.20.0.102
  payment:
    image: weaveworksdemos/payment:0.4.3
    labels:
      com.up9.tapped: true
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    networks:
      wsbridge:
        ipv4_address: 10.20.0.15
  payment_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/payment.hcl
      CENTRAL_CONFIG: /central_config/payment.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "payment_v1"]
    network_mode: "service:payment"
  user:
    image: weaveworksdemos/user:0.4.4
    labels:
      com.up9.tapped: true
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
    networks:
      wsbridge:
        ipv4_address: 10.20.0.16
  user_proxy:
    image: gcr.io/up9-docker-hub/consul-envoy:v1.9.1-v1.16.2
    environment:
      CONSUL_HTTP_ADDR: 10.20.0.2:8500
      CONSUL_GRPC_ADDR: 10.20.0.2:8502
      SERVICE_CONFIG: /config/user.hcl
      CENTRAL_CONFIG: /central_config/user.defaults.hcl
    volumes:
    - "./service_config:/config"
    - "./central_config:/central_config"
    command: ["consul", "connect", "envoy", "-sidecar-for", "user_v1"]
    network_mode: "service:user"
  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      wsbridge:
        ipv4_address: 10.20.0.116
  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    cap_drop:
      - all
    read_only: true
    hostname: user-simulator
    #command: "-d 60 -r 200 -c 2 -h edge-router"
    command: "-d 60 -r 200 -c 2 -h edge:8000"
    networks:
      wsbridge:
        ipv4_address: 10.20.0.103
networks:
    wsbridge:
        driver: bridge
        ipam:
            config:
            - subnet: 10.20.0.0/16
